---
title: "Prac 1"
author: "Thashin Pillay"
format: html
editor: visual
---

```{r}

# ============================
# Installing projrsimple
# ============================

if (!requireNamespace("remotes", quietly = TRUE)) {
  install.packages("remotes")
}
remotes::install_github("MiguelRodo/projrsimple")

# ============================
# Initializing Project
# ============================

library(projrsimple)

projr_init(
  dir_raw_data = "_raw_data",
  dir_cache = "_tmp",
  dir_docs = "docs",
  dir_output = "_output",
  dir_reference = "_reference",
  init_git = TRUE,
  git_add_and_commit_all = TRUE,
  init_readme = TRUE,
  init_github = FALSE,
  github_private = TRUE
)
```

# ============================

# Codes for Practical One

# ============================

## 1.Identifying Missing Values with rows in `airquality`

```{r}
data("airquality")
missing_rows <- airquality[!complete.cases(airquality), ] #swaps complete cases to find missing values
missing_rows
```

------------------------------------------------------------------------

## 2.Summaries for Temperature and Ozone

```{r}

temp_sum <- c(
  mean_temp = mean(airquality$Temp, na.rm = TRUE),
  sd_temp = sd(airquality$Temp, na.rm = TRUE),
  min_temp = min(airquality$Temp, na.rm = TRUE),
  max_temp = max(airquality$Temp, na.rm = TRUE)
)

ozone_sum <- c(
  mean_ozone = mean(airquality$Ozone, na.rm = TRUE),
  sd_ozone = sd(airquality$Ozone, na.rm = TRUE),
  min_ozone = min(airquality$Ozone, na.rm = TRUE),
  max_ozone = max(airquality$Ozone, na.rm = TRUE)
)

temp_sum
ozone_sum

```

## 3.Linear regression estimate

```{r}

data("cars")

Y <- cars$dist
X <- cbind(1, cars$speed) #creates matrix for speed

beta_est <- solve(t(X) %*% X) %*% t(X) %*% Y #uses formula given for estimates
beta_est
```

## 4. Using lm() for estimates

```{r}

lm_model <- lm(dist ~ speed, data = cars) #makes use of the lm() function
summary(lm_model)$coefficients
```

### The estimates found are the same.
